version: '3'
services:
  client1:
    build: ./Client
    links:
      - server
    ports:
      - "5001:22"
    volumes:
      - ./Client:/home
#    command: sh /home/AlphaClient.sh
  client2:
    build: ./Client
    links:
      - server
    ports:
      - "5002:22"
    volumes:
      - ./Client:/home
#    command: sh /home/AlphaClient.sh
  server:
    build: ./Client
    volumes:
      - ./Server:/home
    ports:
      - "5000:22"
